version: '3.4'

services:
  dataengdashboard:
    build: 
      context: .
      dockerfile: ./Dockerfile
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports: ['5000:5000']
    volumes: ['.:/app']
